// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: rabbitmq_writer.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RabbitmqWriter_PublishToRabbitMQ_FullMethodName = "/RabbitmqWriter/PublishToRabbitMQ"
)

// RabbitmqWriterClient is the client API for RabbitmqWriter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RabbitmqWriterClient interface {
	PublishToRabbitMQ(ctx context.Context, in *RabbitmqMessage, opts ...grpc.CallOption) (*RabbitmqResponse, error)
}

type rabbitmqWriterClient struct {
	cc grpc.ClientConnInterface
}

func NewRabbitmqWriterClient(cc grpc.ClientConnInterface) RabbitmqWriterClient {
	return &rabbitmqWriterClient{cc}
}

func (c *rabbitmqWriterClient) PublishToRabbitMQ(ctx context.Context, in *RabbitmqMessage, opts ...grpc.CallOption) (*RabbitmqResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RabbitmqResponse)
	err := c.cc.Invoke(ctx, RabbitmqWriter_PublishToRabbitMQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RabbitmqWriterServer is the server API for RabbitmqWriter service.
// All implementations must embed UnimplementedRabbitmqWriterServer
// for forward compatibility.
type RabbitmqWriterServer interface {
	PublishToRabbitMQ(context.Context, *RabbitmqMessage) (*RabbitmqResponse, error)
	mustEmbedUnimplementedRabbitmqWriterServer()
}

// UnimplementedRabbitmqWriterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRabbitmqWriterServer struct{}

func (UnimplementedRabbitmqWriterServer) PublishToRabbitMQ(context.Context, *RabbitmqMessage) (*RabbitmqResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishToRabbitMQ not implemented")
}
func (UnimplementedRabbitmqWriterServer) mustEmbedUnimplementedRabbitmqWriterServer() {}
func (UnimplementedRabbitmqWriterServer) testEmbeddedByValue()                        {}

// UnsafeRabbitmqWriterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RabbitmqWriterServer will
// result in compilation errors.
type UnsafeRabbitmqWriterServer interface {
	mustEmbedUnimplementedRabbitmqWriterServer()
}

func RegisterRabbitmqWriterServer(s grpc.ServiceRegistrar, srv RabbitmqWriterServer) {
	// If the following call pancis, it indicates UnimplementedRabbitmqWriterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RabbitmqWriter_ServiceDesc, srv)
}

func _RabbitmqWriter_PublishToRabbitMQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RabbitmqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RabbitmqWriterServer).PublishToRabbitMQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RabbitmqWriter_PublishToRabbitMQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RabbitmqWriterServer).PublishToRabbitMQ(ctx, req.(*RabbitmqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// RabbitmqWriter_ServiceDesc is the grpc.ServiceDesc for RabbitmqWriter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RabbitmqWriter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RabbitmqWriter",
	HandlerType: (*RabbitmqWriterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishToRabbitMQ",
			Handler:    _RabbitmqWriter_PublishToRabbitMQ_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rabbitmq_writer.proto",
}
