apiVersion: v1
kind: Service
metadata:
  name: kafka-writer
spec:
  selector:
    app: kafka-writer
  ports:
    - name: grpc
      protocol: TCP
      port: 50052
      targetPort: 50052
  type: ClusterIP
