apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-writer
spec:
  selector:
    app: rabbitmq-writer
  ports:
    - name: grpc
      protocol: TCP
      port: 50053
      targetPort: 50053
  type: ClusterIP
