apiVersion: v1
kind: Service
metadata:
  name: api-rust-service
  namespace: default
spec:
  selector:
    app: api-rust
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
