apiVersion: v1
kind: Service
metadata:
  name: go-orchestrator-service
spec:
  selector:
    app: go-orchestrator
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: 50051
  type: ClusterIP
